Remove DEVELOPMENT flag since it changes Lexical behavior
In development mode, Lexical freezes the selection objects, including _cachedNodes. When your code tried to modify _cachedNodes, it threw:

  TypeError: Cannot assign to read only property '_cachedNodes' of object '#<_NodeSelection>'

Related https://github.com/basecamp/lexxy/pull/507#issuecomment-3710106401

Also, always generate source maps